### PR TITLE
options/posix: Implement tdestroy

### PR DESCRIPTION
**Pull request by Qwinci**

### CODE REVIEW

**Review by no92 — APPROVED** [review]
LGTM

**Review by Geertiebear — COMMENTED** [review]
Add a test

**Comment by Qwinci** [comment]
I added a test that checks how many times the free function is called, I am not sure if there are any other meaningful tests that could be done. Also this fixes #351

**Comment by no92** [comment]
The referenced issue is about `tdelete`, not `tdestroy` though.

**Comment by Qwinci** [comment]
> The referenced issue is about `tdelete`, not `tdestroy` though.

Wait yeah, they have similar enough names and there was a comment which referenced that issue above the commented out `tdestroy` line so I assumed it was that.

**Review by 64 — APPROVED** [review]

**Review by mintsuki — APPROVED** [review]

**Pull request merged**
