### PR TITLE
build: Add disable_libgcc_dependency meson option

### PR DESCRIPTION
**Pull request by mintsuki**

### CODE REVIEW

**Review by Geertiebear — APPROVED** [review]
LGTM, what is the usecase for this?

**Review by ArsenArsen — CHANGES_REQUESTED** [review]
logical operators exist, you can use those (as well as a toolchain that isn't broken enough to require this flag)

**Comment by mintsuki** [comment]
I know full well what I am doing. The toolchain is not broken.

**Comment by mintsuki** [comment]
> LGTM, what is the usecase for this?

@Geertiebear So that the build system won't hard depend on a search path available libgcc and I can manually pass a prebuild libgcc.a without it complaining.

**Comment by mintsuki** [comment]
@ArsenArsen I am not sure what the requested changes are supposed to be.

**Comment by ArsenArsen** [comment]
> @ArsenArsen I am not sure what the requested changes are supposed to be.

```
if a
    if b
    endif
endif
```

to

```
if a and b
endif
```

**Comment by mintsuki** [comment]
> > @ArsenArsen I am not sure what the requested changes are supposed to be.
> 
> ```
> if a
>     if b
>     endif
> endif
> ```
> 
> to
> 
> ```
> if a and b
> endif
> ```

@ArsenArsen I'm not sure where you think doing that would be beneficial in this patch.

**Comment by lukflug** [comment]
Since both conditions are negated, one could use De Morgan to further transform the expression.

**Review by ArsenArsen — APPROVED** [review]
oh, my bad, I misread the indentation level of the original conditions, there's indeed no `if { if { } }`-type nesting

**Pull request merged**
