### PR TITLE
options/posix: move poll(3) from linux option to posix

### PR DESCRIPTION
**Pull request by no92**

### CODE REVIEW

**Review by qookei — COMMENTED** [review]
LGTM, but perhaps it'd be good to remove the `-stubs` infix from `poll-stubs.cpp`, since it doesn't contain any stubs

**Review by qookei — APPROVED** [review]

**Comment by avdgrinten** [comment]
poll() is not in POSIX.

**Comment by qookei** [comment]
```
CONFORMING TO
   poll() conforms to POSIX.1-2001 and POSIX.1-2008.       ppoll() is Linux-specific.
```
https://pubs.opengroup.org/onlinepubs/9699919799/functions/poll.html

**Comment by avdgrinten** [comment]
Ah, I was looking for the wrong header.

By the way, shouldn't the poll.h header be moved too?

**Comment by qookei** [comment]
Oh true, that header should be moved as well

**Comment by no92** [comment]
The `poll.h` header is already part of the posix options.

**Pull request merged**
