### PR TITLE
ansi: add RE_DUP_MAX and CHARCLASS_NAME_MAX

### PR DESCRIPTION
**Pull request by 64**
Commit taken from the Vinix patches.

### CODE REVIEW

**Comment by avdgrinten** [comment]
Are these defined by any standard?

**Comment by 64** [comment]
They are both regex-related and defined by posix.

**Review by Geertiebear — APPROVED** [review]
LGTM then.

**Comment by ArsenArsen** [comment]
One of these is sysconf-able, that should have a matching _SC and respective handling (also, the commit message doesn't explain anything)

**Review by ArsenArsen — APPROVED** [review]

**Pull request merged**
