### PR TITLE
sysdeps/managarm: hack sys_gettid

### PR DESCRIPTION
**Pull request by 64**
This should unbreak the CI.

### CODE REVIEW

**Comment by ArsenArsen** [comment]
is this really a hack? also, if this function is required, we should probably make it strong

**Comment by 64** [comment]
Well, it's a hack because each thread should have a unique TID but the same PID, right?

**Comment by ArsenArsen** [comment]
IIRC, getpid() returns TID currently on managarm, which is what I mean. I could be misremembering, though.

**Comment by 64** [comment]
Even if it does, that should be fixed in managarm + a new GET_TID request type should be added for use in `gettid`. In any case, the code here should be changed later.

**Review by Geertiebear — APPROVED** [review]

**Pull request merged**
