### PR TITLE
options/rtdl: Take all objects into account in __dlapi_reverse

### PR DESCRIPTION
**Pull request by Qwinci**

### CODE REVIEW

**Review by ikbenlike — APPROVED** [review]
looks good to me, LGTM if CI approves

**Comment by no92** [comment]
There's a typo in the commit title, `rtld` instead of `rtdl`.

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
Looks good but the comment from
Leo needs to be addressed

**Review by Dennisbonke — APPROVED** [review]
LGTM now

**Pull request merged**
