### PR TITLE
sysdeps/linux: Add sys_yield

### PR DESCRIPTION
**Pull request by Dennisbonke**
Part of the mlibc LFS project.

### CODE REVIEW

**Comment by ArsenArsen** [comment]
Maybe we should adjust this function to match POSIX (return int, never fail on Linux)

**Comment by 64** [comment]
> Maybe we should adjust this function to match POSIX (return int, never fail on Linux)

Yes, I agree

**Comment by avdgrinten** [comment]
Why? `void` expresses correctly that the function can't fail.

**Comment by ArsenArsen** [comment]
> Why? `void` expresses correctly that the function can't fail.

Except on systems where it can (permitted by POSIX)

**Comment by avdgrinten** [comment]
I think POSIX is overly pessimistic here; an empty function is a valid implementation for `sched_yield()`.

**Review by 64 — APPROVED** [review]

**Pull request merged**
