### PR TITLE
sysdeps: Remove qword

### PR DESCRIPTION
**Pull request by mintsuki**

### CODE REVIEW

**Comment by YusufKhan-gamedev** [comment]
replace with f-word

**Comment by pitust** [comment]
Why are you removing the qword port? It's a nice sample port that you can use as a reference.

**Comment by YusufKhan-gamedev** [comment]
> Why are you removing the qword port? It's a nice sample port that you can use as a reference.

Yes, we just ctrl c ctrl v it

**Comment by LittleCodingFox** [comment]
Yeah I used qword as a base for mine

**Comment by Geertiebear** [comment]
Closing in favour of #664.

**Pull request closed without merging**
