### PR TITLE
options/rtdl: Implement R_IRELATIVE relocation

### PR DESCRIPTION
**Pull request by Qwinci**

### CODE REVIEW

**Review by no92 — CHANGES_REQUESTED** [review]
This would either need guarding by `#ifdef`s or something similar as this has quirks for aarch64 and RISC-V.

**Comment by Qwinci** [comment]
> This would either need guarding by `#ifdef`s or something similar as this has quirks for aarch64 and RISC-V.

I converted the late relocation handling to use the Relocation type and moved R_IRELATIVE handling to there because they are supposed to be processed after all other relocations. Also added `#ifdef`s for x86_{x64} and aarch64 (though that implementation doesn't properly pass in the hwcaps as the first argument and always just passes a zero).

**Review by no92 — APPROVED** [review]
LGTM

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Pull request merged**
