### PR TITLE
termios-stub.cpp: make sure _GNU_SOURCE is defined

### PR DESCRIPTION
**Pull request by moodyhunter**
need to get CBAUD, etc.

### CODE REVIEW

**Comment by Geertiebear** [comment]
Not entirely sure if I understand the issue that this solves, could you elaborate?

**Comment by moodyhunter** [comment]
Hi, a similar one is at https://github.com/managarm/mlibc/pull/878

A compiler may not define _GNU_SOURCE so we have to define it to get CBAUD defined.

**Review by no92 — APPROVED** [review]
LGTM

**Comment by moodyhunter** [comment]
thanks :)

**Pull request merged**
