### PR TITLE
sysdeps/managarm: Send the O_NOCTTY flag to managarm

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by borrrden** [comment]
Note: This depends on https://github.com/managarm/managarm/pull/442

**Comment by avdgrinten** [comment]
LGTM.

**Comment by ArsenArsen** [comment]
reword the commit? it is currently out-of-line with what we normally do

**Comment by Dennisbonke** [comment]
See https://docs.managarm.org/handbook/contributing/commit-messages.html for commit messages guidelines, something like adding `sysdeps/managarm: <rest of message>` would make it a lot better already.

**Comment by borrrden** [comment]
Apologies, I thought that commit style was just for managarm.  I didn't notice it here as well.

**Pull request merged**
