### PR TITLE
rtdl: Use mprotect to remove superfluous permissions

### PR DESCRIPTION
**Pull request by streaksu**
In the name of security.

Tested on Ironclad and Lyre, where it worked, I would appreciate if someone tried it on linux or managarm for completeness

### CODE REVIEW

**Comment by qookei** [comment]
CI passed so it works on Linux on all supported architectures

**Review by no92 — APPROVED** [review]

**Review by qookei — APPROVED** [review]

**Review by ArsenArsen — APPROVED** [review]

**Comment by avdgrinten** [comment]
Why do we need to add `PROT_WRITE` here if the current code doesn't do it?

**Comment by qookei** [comment]
We memset the area after the data from the file with 0, and in the `!MLIBC_MAP_DSO_SEGMENTS` we map with `|PROT_WRITE` since we need to copy data into it. The code to drop perms was added outside of that check so it applies to both cases,

**Comment by avdgrinten** [comment]
Ah, so the old code simply doesn't work if there are read-only segments with file size != mem size.

**Comment by qookei** [comment]
Presumably, although we assume vm_map hands out zeroed memory? So in theory the memset shouldn't be needed.

**Comment by avdgrinten** [comment]
The memset is needed to clear out the tail of the last page that is still part of the file.

**Comment by qookei** [comment]
Ah alright. This PR seems good to merge then.

**Pull request merged**
