### PR TITLE
options/ansi: Avoid multiple definition errors in math.h

### PR DESCRIPTION
**Pull request by Dennisbonke**
This issue came to light when compiling `libvpx`, and this seems to fix the problems.

### CODE REVIEW

**Comment by 64** [comment]
I think we reached the conclusion that it's sufficient to just mark the functions as `static __inline__` and keep them in the header

**Comment by Dennisbonke** [comment]
> I think we reached the conclusion that it's sufficient to just mark the functions as `static __inline__` and keep them in the header
> 
> The issue arises from gnu89 treating inline functions differently to c99. Maybe a comment should be added to this effect (explaining why we use `__inline__`)

Would this constitute an ABI break? Don't think so right?

**Comment by 64** [comment]
According to @ArsenArsen: no, because those symbols aren't present in libc.so (since they're never used by us internally)

**Comment by 64** [comment]
And frankly while we're at it, we could just do what glibc does and use the gcc builtins?

https://github.com/bminor/glibc/blob/118a2aee07f64d605b6668cbe195c1f44eac6be6/math/math.h#L1299-L1310

**Review by Geertiebear — CHANGES_REQUESTED** [review]
Please adjust this PR to the strategy discussed on Discord.

**Comment by Dennisbonke** [comment]
Performed the requested changes, tested `libvpx` and that builds successfully. Should be good to go now.

**Pull request merged**
