### PR TITLE
options/posix: fix ABI for `_SC_*` defines

### PR DESCRIPTION
**Pull request by no92**

### CODE REVIEW

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
LGTM but this is a full ABI break and therefor should go against abi-break

**Comment by avdgrinten** [comment]
The commit history is broken.

**Comment by no92** [comment]
That was due to switching the target branch, has been fixed now.

**Comment by qookei** [comment]
This is pretty pedantic, but our ABI for this was not broken, and as such, we're not fixing anything (we're just making it compatible with glibc). Could you reword the commit?

**Comment by no92** [comment]
> Could you reword the commit?

Done.

**Review by qookei — APPROVED** [review]

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Pull request merged**
