### PR TITLE
meta: rename ANSI option to ANSI tests option

### PR DESCRIPTION
**Pull request by no92**
As disabling the ANSI option makes no sense, convert the option to only disable ANSI option tests.

### CODE REVIEW

**Review by qookei — COMMENTED** [review]
`disable_ansi_tests_option` -> `disable_ansi_option_tests`? It's tests for the ANSI option after all.

**Comment by no92** [comment]
Renamed the option as requested.

**Review by qookei — APPROVED** [review]

**Comment by Geertiebear** [comment]
I'd be more in favour of removing this option completely, it seems weird to me to disable specifically the ansi tests.

**Comment by mintsuki** [comment]
I believe #1146 fixes this.

**Pull request closed without merging**
