### PR TITLE
options/posix: fix pthread syscall cancellation

### PR DESCRIPTION
**Pull request by Geertiebear**

### CODE REVIEW

**Comment by avdgrinten** [comment]
What kind of issue is fixed by this PR?

**Comment by Geertiebear** [comment]
This is something that was supposed to work with #230, but the behaviour wasn't implemented correctly in that PR. This PR fixes that.

**Comment by avdgrinten** [comment]
Okay, but what exactly does it fix? What aspect of the feature was broken before?

**Comment by Geertiebear** [comment]
Deferred cancellation never interrupted blocking syscalls properly. Only asynchronous did. This PR fixes that issue, and adds a small test case for it.

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Pull request merged**
