### PR TITLE
sysdeps: Fix sp assignment in sys_prepare_stack

### PR DESCRIPTION
**Pull request by Qwinci**
Change sp assignment in sys_prepare_stack in case `*stack` is not null to `*stack + *stack_size`, because *stack points to the bottom of the stack and not top. As it is currently the writes later down in this function would be out of bounds in that case.

### CODE REVIEW

**Review by Geertiebear — APPROVED** [review]
LGTM, thanks for fixing this mistake! (woops lol)

**Comment by Geertiebear** [comment]
Could you please squash the sysdep commits into the actual commit that changed the sysdep?

**Comment by Qwinci** [comment]
> Could you please squash the sysdep commits into the actual commit that changed the sysdep?

Done. There is the managarm sysdep fix commit that was made before the signature change, should it be kept or do I squash it too?

**Comment by Geertiebear** [comment]
That can be kept, it has nothing to do with the change in the sysdep signature.

**Pull request merged**
