### PR TITLE
{options,sysdeps}/linux: implement ptrace

### PR DESCRIPTION
**Pull request by 64**
This is part of the mlibc on Linux project.

### CODE REVIEW

**Comment by 64** [comment]
I think that's a false positive on the ABI checker.

**Comment by ArsenArsen** [comment]
The members did change, maybe this warning would be avoided if the old aliases remained?
Whether this matters also depends on the ucontext consumers

**Comment by 64** [comment]
Well, that is true but it shouldn't count as an ABI break

**Comment by Geertiebear** [comment]
Seeing as this is both how glibc and musl define the struct layout to be, I don't think that there will be any downstream API issues.

**Review by Geertiebear — APPROVED** [review]
LGTM, merging this with the knowledge that the previous ``mcontext_t`` definition was incorrect.

**Pull request merged**
