### PR TITLE
options/posix: implement getpw{nam,uid}_r

### PR DESCRIPTION
**Pull request by 64**
Fixes managarm/mlibc#185 and managarm/mlibc#191.

### CODE REVIEW

**Comment by Geertiebear** [comment]
LGTM although I wonder if there is a way we can auto test this?

**Comment by 64** [comment]
> LGTM although I wonder if there is a way we can auto test this?

I think it would be hard without some kind of container to test in (maybe that would be a good idea in the long term?)

**Comment by Geertiebear** [comment]
Yeah, I don't think I see another way either.

**Comment by avdgrinten** [comment]
I guess we could add a test that checks whether the root user exists or not.

**Comment by 64** [comment]
Ok, done

**Comment by Geertiebear** [comment]
Then LGTM

**Pull request merged**
