### PR TITLE
options/posix: implement {get,set,end}usershell

### PR DESCRIPTION
**Pull request by Mathewnd**
Needed for ``su -``. Used the pwd code as a reference.

### CODE REVIEW

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
LGTM, but missing tests.

**Review by Geertiebear — APPROVED** [review]
LGTM

**Review by Geertiebear — CHANGES_REQUESTED** [review]
On second thought, some tests would be nice

**Review by no92 — APPROVED** [review]
LGTM

**Pull request merged**
