### PR TITLE
Implement memfd and file sealing

### PR DESCRIPTION
**Pull request by no92**
This is the mlibc counterpart to managarm/managarm#418.

### CODE REVIEW

**Review by avdgrinten — APPROVED** [review]
LGTM, can be merged after Managarm changes have landed.

**Comment by no92** [comment]
Minor changes to allow for both headers to be used for `memfd_create`.

**Comment by avdgrinten** [comment]
Linux headers typically do not contain functions. Why is this done?

**Comment by no92** [comment]
An old `mesa` included `linux/memfd.h` expecting memfd_create to be defined there, while not including `sys/mman.h`.

**Comment by avdgrinten** [comment]
But even on Linux, `linux/memfd.h` does not have the function, does it? So we should not add it there either.

**Comment by no92** [comment]
Fair enough, moved `memfd_create` to `sys/mman.h`.

**Pull request merged**
