### PR TITLE
ci: build libgcc

### PR DESCRIPTION
**Pull request by 64**
Now that we have `sys/syscall.h`, this should work.

### CODE REVIEW

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Comment by 64** [comment]
libgcc builds now, but libstdc++ still doesn't. I'm not sure if that requires some patching.

**Comment by ArsenArsen** [comment]
looks like it doesn't know what system it's being built on (that header is included on gnu/linux)

```diff
diff --git a/libstdc++-v3/configure.host b/libstdc++-v3/configure.host
index ec32980aa..1fe59f392 100644
--- a/libstdc++-v3/configure.host
+++ b/libstdc++-v3/configure.host
@@ -255,7 +255,7 @@ case "${host_os}" in
   freebsd*)
     os_include_dir="os/bsd/freebsd"
     ;;
-  linux-musl*)
+  linux-musl* | linux-mlibc*)
     os_include_dir="os/generic"
     ;;
   gnu* | linux* | kfreebsd*-gnu | uclinux*)
```

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Pull request merged**
