### PR TITLE
sysdeps: remove qword

### PR DESCRIPTION
**Pull request by 64**
Supercedes #340.

### CODE REVIEW

**Review by avdgrinten — APPROVED** [review]

**Review by Geertiebear — APPROVED** [review]

**Comment by 64** [comment]
The CI needs to be adjusted so that `qword` isn't a required check anymore. Also, `mlibc-shared` and `vinix` should be made required checks.

**Comment by ArsenArsen** [comment]
fits in this PR, do push those changes

**Comment by 64** [comment]
> fits in this PR, do push those changes

That's a GitHub setting, not something I can change in this PR

**Comment by ArsenArsen** [comment]
ah, my bad, I thought you meant in tree

**Pull request merged**
