### PR TITLE
build: Add C standard (as GNU11) to root meson.build file

### PR DESCRIPTION
**Pull request by mintsuki**

### CODE REVIEW

**Comment by no92** [comment]
What exactly is the motivation for this? Do we use C features that require at least C11?

**Comment by mintsuki** [comment]
It is always advisable to specify the C version to use. Without this, meson just does not pass `-std=...` altogether to the C compiler driver, which can cause issues in the future if the default C version used by the compiler changes (for gcc, it is currently GNU17).

**Comment by no92** [comment]
That's a fair point. I do wonder what the actual minimal required C std is that mlibc needs; if I have enough time, I'll try to investigate.

**Comment by mintsuki** [comment]
I think this is fine to merge as is, for now. The need for GNU11 over C11 is because there are uses of the `asm` keyword and other stuff that may rely on the GNU variant.

**Pull request merged**
