### PR TITLE
options/posix: Implement setresuid and setresgid

### PR DESCRIPTION
**Pull request by Dennisbonke**
Split off from #544

Part of the mlibc LFS project.

### CODE REVIEW

**Comment by 64** [comment]
Did you forget to implement these functions in the Linux sysdeps?

**Comment by Dennisbonke** [comment]
> Did you forget to implement these functions in the Linux sysdeps?

Was intentional, pending rebase of LFS on sysdep changes. Those will follow in a later PR.

**Comment by 64** [comment]
These should use MLIBC_CHECK_OR_ENOSYS now (might need to rebase).

**Comment by no92** [comment]
For the sake of keeping rebases simpler on our lfs branch, not using `MLIBC_CHECK_OR_ENOSYS` for now should be fine IMO. I do promise to make the sysdeps use `MLIBC_CHECK_OR_ENOSYS` after all the sysdeps on the lfs branch are PRed and merged into master. I will try to get the PRs for the sysdeps opened today.

**Pull request merged**
