### PR TITLE
sysdeps: add reminder to call __dlapi_enter for static builds to work properly

### PR DESCRIPTION
**Pull request by 64**
This should reduce some confusion for new ports.

### CODE REVIEW

**Comment by Geertiebear** [comment]
Why not just add the correct call to the sysdeps, instead of this PR?

**Comment by 64** [comment]
I think it requires kernel support to pass the stack in, right?

**Comment by avdgrinten** [comment]
No kernel support is needed but a change in `crt*.o` (which is a serious ABI break as it's compiled into each and every program).

**Review by Geertiebear — APPROVED** [review]
Then adding a reminder is fine.

**Pull request merged**
