### PR TITLE
Implement FIONREAD ioctl

### PR DESCRIPTION
**Pull request by no92**
Implement the `FIONREAD` ioctl. This depends on the other half of the PR in managarm, managarm/managarm#410.

This obsoletes #241.

### CODE REVIEW

**Review by avdgrinten — APPROVED** [review]
LGTM. argp = NULL is allowed by the ioctl?

**Comment by no92** [comment]
I can't find any instance or mention of `argp` being NULL, so we might need to check this.

**Comment by no92** [comment]
Added a check that returns `EINVAL` for NULL `argp`.

**Comment by avdgrinten** [comment]
Minor nitpick: if we return EINVAL, we can simply return it before doing a request.

**Comment by no92** [comment]
Amended the commit to return on `!argp` before making requests.

**Review by avdgrinten — APPROVED** [review]
LGTM now.

**Pull request merged**
