### PR TITLE
mlibc: fix tcsetpgrp

### PR DESCRIPTION
**Pull request by ElectrodeYT**

### CODE REVIEW

**Comment by Dennisbonke** [comment]
Holding until @ElectrodeYT confirms this doesn't break Linux.

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
As stated, holding temporarily.

**Comment by ElectrodeYT** [comment]
Should now no longer affect linux.

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Review by no92 — APPROVED** [review]
LGTM

**Pull request merged**
