### PR TITLE
Implement lockf and fixed a bug in environment handling

### LINKED ISSUE #169: lockf() unimplemented
On managarm, `xbps` requires `lockf()`, which is unimplemented.

### PR DESCRIPTION
**Pull request by Dennisbonke**
This PR fixes a bug in the handling of environment variables found while working with `gtk3` on managarm. Furthermore, it implements `lockf()` like musl.

This PR fixes #169

### CODE REVIEW

**Review by avdgrinten — COMMENTED** [review]
LGTM. If the code is taken literally from musl, add a comment (the license allows this but we need to clarify the copyright status).

**Comment by Dennisbonke** [comment]
Yeah that makes sense, I've added a comment that the code is from musl.

**Comment by Geertiebear** [comment]
Hmm on linux ``lockf`` boils down to a ``fcntl`` but maybe we should have it as a sysdep instead? Other platforms might not implement it as a ``fcntl``

**Comment by avdgrinten** [comment]
That could be done but OTOH it would probably lead to duplication of this code in multiple sysdeps. I think for now it's better to go with the Linux-style implementation.

**Pull request merged**
