### PR TITLE
options/posix: Define quad_t and u_quad_t

### PR DESCRIPTION
**Pull request by Dennisbonke**
Split off from #544

Part of the mlibc LFS project.

### CODE REVIEW

**Comment by 64** [comment]
Conflicts.

**Review by ArsenArsen — CHANGES_REQUESTED** [review]
This definition is also not necessarily accurate, from OpenBSD:
```c
/* quads, deprecated in favor of 64 bit int types */
typedef	__int64_t	quad_t;
typedef	__uint64_t	u_quad_t;
```

These appear to also be BSD specifics? I can't find anything about it in POSIX.

**Comment by Dennisbonke** [comment]
> This definition is also not necessarily accurate, from OpenBSD:
> 
> ```c
> /* quads, deprecated in favor of 64 bit int types */
> typedef	__int64_t	quad_t;
> typedef	__uint64_t	u_quad_t;
> ```
> 
> These appear to also be BSD specifics? I can't find anything about it in POSIX.

While the BSD stuff might be accurate, this is how musl and glibc define them.

**Comment by ArsenArsen** [comment]
Sure, but I reckon BSD is the authoritative source on BSD extensions

**Comment by Dennisbonke** [comment]
> Sure, but I reckon BSD is the authoritative source on BSD extensions

I'll change them.

**Comment by avdgrinten** [comment]
`musl` defines them as (`unsigned`) `long long`. We can probably use `__mlibc_int64` / `__mlibc_uint64`.

**Comment by avdgrinten** [comment]
Also, add a comment to state that these are BSD extensions.

**Comment by Dennisbonke** [comment]
> musl defines them as (`unsigned`) `long long`. We can probably use `__mlibc_int64` / `__mlibc_uint64`.

We already have stdint.h in that file, so I used `int64_t` / `uint64_t` if that is alright.

**Review by ArsenArsen — APPROVED** [review]
(u)int64_t is defined at this point in the header, so this is fine

**Review by avdgrinten — APPROVED** [review]

**Comment by Geertiebear** [comment]
This can be rebased to fix the tests.

**Pull request merged**
