### PR TITLE
implement `malloc_usable_size`

### PR DESCRIPTION
**Pull request by no92**
Hard-depends on managarm/frigg#59. CI will also fail until that is merged.

### CODE REVIEW

**Comment by Geertiebear** [comment]
As discussed on discord, this change might not even be desirable, and uses of ``malloc)usable_size()`` should probably be fixed in upstream packages.

**Comment by no92** [comment]
Given as glibc, mlibc and bionic support it and systemd uses it (correctly now, since version 253) I don't see a lot of room for calling this not desirable, especially given that the implementation is trivial and doesn't involve additional overhead.

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Review by ikbenlike — CHANGES_REQUESTED** [review]
from my understanding this is a GNU extension, not linux-specific. if that is the case it should probably go in the glibc option

**Comment by Dennisbonke** [comment]
> from my understanding this is a GNU extension, not linux-specific. if that is the case it should probably go in the glibc option

Good catch, the man page seems to agree. We should probably move this to the glibc option indeed.

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
We should move this to the glibc option.

**Comment by no92** [comment]
Moved the function to `options/glibc`.

**Review by Geertiebear — APPROVED** [review]
LGTM.

**Pull request merged**
