### PR TITLE
options/ansi: fix strtol et al., implement wcstol et al.

### PR DESCRIPTION
**Pull request by 64**
This PR fixes the current implementation of `strtol` and friends by replacing it with a generic implementation in idiomatic C++. It also adds a much more comprehensive set of tests.

When testing it was discovered that this commit somehow triggers an issue in `read_dns_name`, so we also fix that.

Fixes https://github.com/managarm/mlibc/issues/467.

### CODE REVIEW

**Review by Geertiebear — COMMENTED** [review]
LGTM except for one style nitpick.

**Comment by Geertiebear** [comment]
Could you squash the fixup commit please?

**Comment by 64** [comment]
Done.

**Comment by 64** [comment]
Merging this since it was already approved.

**Pull request merged**
