### PR TITLE
meta: fix all warnings and enable -Werror on CI

### PR DESCRIPTION
**Pull request by 64**
Supercedes https://github.com/managarm/mlibc/pull/436.

### CODE REVIEW

**Comment by Dennisbonke** [comment]
LGTM, one question, does this also enable `-Wall` and `-Wextra`? If not, we should do that too.

**Review by no92 — APPROVED** [review]

**Comment by 64** [comment]
> LGTM, one question, does this also enable `-Wall` and `-Wextra`? If not, we should do that too.

We already have `warning_level=2` in the meson.build

**Comment by Dennisbonke** [comment]
> > LGTM, one question, does this also enable `-Wall` and `-Wextra`? If not, we should do that too.
> 
> We already have `warning_level=2` in the meson.build

Awesome, then this should be good to go from my point of view.

**Review by Geertiebear — APPROVED** [review]
LGTM.

**Pull request merged**
