### PR TITLE
options/posix: handle EAGAIN in sem_wait

### PR DESCRIPTION
**Pull request by 64**

### CODE REVIEW

**Review by ArsenArsen — APPROVED** [review]
not sure if the error reporting should necessarily be a crash for misc errors, but this is an improvement

**Comment by 64** [comment]
> not sure if the error reporting should necessarily be a crash for misc errors, but this is an improvement

I think this is correct for EAGAIN, but EINTR I think we need to return and set errno?

**Review by Geertiebear — CHANGES_REQUESTED** [review]
I think ``EINTR`` we do need to report, it would be good to do it in this PR too.

**Comment by 64** [comment]
FIxed this to handle EINTR properly.

**Review by Geertiebear — APPROVED** [review]

**Pull request merged**
