### PR TITLE
Fix sem_trywait and linux sysdep pselect

### PR DESCRIPTION
**Pull request by Qwinci**

### CODE REVIEW

**Review by Geertiebear — COMMENTED** [review]
Thanks for the fixes! How difficult is writing a regression test for this?

**Comment by Qwinci** [comment]
> Thanks for the fixes! How difficult is writing a regression test for this?

Probably not that hard, Ill write some tests for the semaphores.

**Comment by Geertiebear** [comment]
Does that also include a regression test for the bug on ``sem_trywait()``?

**Comment by Qwinci** [comment]
> Does that also include a regression test for the bug on `sem_trywait()`?

Yes, the one that does 4 sem_trywaits in a row on a semaphore that only has 3 count. That would be where the fourth sem_trywait would incorrectly return 0 and the counter would wrap around.

**Review by Geertiebear — APPROVED** [review]

**Pull request merged**
